### ISSUE TITLE
Idea: remove `map(b: Ascribed => b)` when widening but the type is covariant

### ISSUE THREAD

**Issue by kubukoz** [oleg-py/better-monadic-for#29]
e.g.

```scala
for {
  l <- List(1, 2, 3)
} yield l: Any
```

**Comment by oleg-py** [comment]
I've looked into this and it might be not worth the trouble.

Altering things post typechecking is very fragile and causes unexpected crashes in more complex examples, even when substituted by a subtype, so I'd have to manually change types of things, or retypecheck it somehow for tree to end up being `List(1, 2, 3): List[Any]`. That's why map removing is very conservative, and its primary focus is to enable monadic recursion with for-comprehension that doesn't cause OOM.

I might reconsider it if there are compelling cases, but I haven't encountered one yet.

**Comment by kubukoz** [comment]
Makes sense :)
