### ISSUE TITLE
Compilation error while flatmapping JSValue

### ISSUE THREAD

**Issue by kamilkloch** [oleg-py/better-monadic-for#34]
The following code
```scala
import org.json4s._
import org.json4s.jackson.JsonMethods._

val json = parse(...)

val bidsAndAsks1 = for {
    JObject(child) <- json
    JField("symbol", JString(name)) <- child
    ...
} yield ...
```
produces
```
[error] CustomResources.scala:108:20: value flatMap is not a member of org.json4s.JValue
[error]     JObject(child) <- json
[error]                    ^
[error] one error found
```

Compilation succeeds without the plugin. Plugin version `0.3.1`.

**Comment by oleg-py** [comment]
Can't be fixed. This DSL is directly at odds against what better-monadic-for is supposed to do.

json4s heavily relies on the fact that you'd have `withFilter` clause. It provides an implicit conversion to MonadicJValue, which _does not_ have `flatMap`, and then `withFilter` creates a `JValueWithFilter` which does. Because bm4 _whole purpose_ is to remove that `withFilter` call, the conversion never happens. See [here](https://github.com/json4s/json4s/blob/961c4a6bae0d164e243d25780cad4b5b816bf3f5/core/src/main/scala/org/json4s/MonadicJValue.scala#L333). map/flatMap/withFilter both eventually delegate to `filter` of `MonadicJValue` which essentially puts the value into a List and filters that.

That won't be super helpful, however. By removing `withFilter` clause, you don't get to actually filter out values that don't match, and you'll end up crashing with `MatchError`. So, this DSL is incompatible with bm4, period.

In dotty, it would require `case` keyword to be usable as patterns are irrefutable by default (lampepfl/dotty#2578). So you are going to have to write:
```scala
for {
    case JObject(child) <- json
    case JField("symbol", JString(name)) <- child
    ...
} yield ...
```

I looked into adding something similar to bm4, but it is quite a bit of effort, and you're the first to need it in over a year, so no promises it'll ever land here, esp. given that dotty is coming reasonably soon. You'd have to either abandon bm4 or this DSL of json4s.

**Comment by kamilkloch** [comment]
Thanks for the comprehensive and super-fast response!!
