### ISSUE TITLE
Rename/alias implicit0 to `given`?

### ISSUE THREAD

**Issue by REDNBLACK** [oleg-py/better-monadic-for#36]
https://dotty.epfl.ch/blog/2019/09/23/19th-dotty-milestone-release.html#allow-given-in-pattern-bindings

**Comment by oleg-py** [comment]
I expect dotty to render bm4 unnecessary, but I don't want to introduce syntax into it that is different from Scala of today. And today, we have `implicit`. I'll do it if some future Scala 2.x version introduces `given` to ease the migration, but that's not on the radar. Especially since I can't easily change existing usages of `implicit` keyword.

Also, there are some tooling reasons - e.g. Intellij IDEA knows how to recognize `implicit0`, but it won't know about `given` for a while at best.
